version: "3.11"
services:
  db:
    container_name: pg_db
    image: postgres:latest
    volumes:
      - .threads_db./postgres/:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7
    expose:
      - 6379
    ports:
      - "6379:6379"

  web:
    container_name: backend
    restart: always
    build:
      context: ././
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/back_end
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    depends_on:
      - redis