# Use an official Python runtime as a base image
FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /back_end
COPY poetry.lock pyproject.toml /back_end/
RUN pip install -U pip && \
    pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root

# Copy the Django project into the container
COPY . ./
COPY ../.env ./.env

# Run the Celery worker
CMD ["celery", "-A", "config", "worker", "--loglevel=info"]